/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analysis: typeof import('./src/components/Analysis.vue')['default']
    AnalysisPost: typeof import('./src/components/AnalysisPost.vue')['default']
    BlogPost: typeof import('./src/components/BlogPost.vue')['default']
    ChinaDatabase: typeof import('./src/components/ChinaDatabase.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
