/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analysis: typeof import('./src/components/Analysis.vue')['default']
    AnalysisPost: typeof import('./src/components/AnalysisPost.vue')['default']
    BlogPost: typeof import('./src/components/BlogPost.vue')['default']
    Database: typeof import('./src/components/Database.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subscribe: typeof import('./src/components/Subscribe.vue')['default']
  }
}
